export const Categories = [
    { key: null, label: "카테고리 선택" },
    { key: 1,  label: "개발" },
    { key: 2,  label: "클라우드 & 인프라" },
    { key: 3,  label: "AI" },
    { key: 4,  label: "데이터베이스" },
    { key: 5,  label: "CS 지식" },
    { key: 6,  label: "프로젝트" },
    { key: 7,  label: "문제해결(트러블 슈팅)" },
    { key: 8,  label: "성장 기록" },
    { key: 9,  label: "IT 뉴스" },
    { key: 10, label: "기타" },
    { key: 11, label: "스터디" },
    { key: 12, label: "공모전" },
  ];