name: Deploy Frontend

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    uses: Gachon-Univ-Creative-Code-Innovation/infra-configs/.github/workflows/frontend-deploy.yml@main
    with:
      service: frontend-service
      tag: ${{ github.sha }} # 마지막 커밋 해쉬
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      VITE_KAKAO_REST_KEY: ${{ secrets.VITE_KAKAO_REST_KEY }}
      VITE_KAKAO_REDIRECT_URI: ${{ secrets.VITE_KAKAO_REDIRECT_URI }} 
